# Copyright (c) 2009-2013 VMware, Inc.
workloads:
  app_loop_ruby:
    display: create and update rails and sinatra apps

    appnames:
      - please-compute
      - please-compute

    servicenames:
      - please-compute

    operations:
      # login, get situated, run vmc apps and services
      - op: sequence
        actions:
          - action: login
          - action: info

      # create a simple app
      - op: sequence
        actions:
          - action: create_app
            app: foo
            appname: 0

      # create a rails app
      - op: sequence
        actions:
          - action: create_app
            app: db_rails
            appname: 1
            suspended: true
          - action: create_service
            service: mysql
            plan: P200
            servicename: 0
          - action: user_services
          - action: pause
            abs: 1
          - action: pause
            max: 10
          - action: bind_service
            appname: 1
            servicename: 0
          - action: start_app
            appname: 1

      # perform a few updates
      - op: loop
        n: 8
        operations:
          - op: sequence
            actions:
              - action: update_app
                app: foo
                appname: 0

      # delete the apps
      - op: sequence
        actions:
          - action: delete_app
            appname: 0
          - action: delete_app
            appname: 1
          - action: delete_service
            servicename: 0

  app_loop_rails:
    display: create and update a rails app

    appnames:
      - please-compute
    servicenames:
      - please-compute

    operations:
      # login, get situated, run vmc apps and services
      - op: sequence
        actions:
          - action: login
          - action: info

      # create a simple app
      - op: sequence
        actions:
          - action: create_app
            app: db_rails
            appname: 0
            suspended: true
          - action: create_service
            service: mysql
            plan: P200
            servicename: 0
          - action: user_services
          - action: pause
            abs: 1
          - action: pause
            max: 4
          - action: bind_service
            appname: 0
            servicename: 0
          - action: start_app
            appname: 0
          - action: update_app
            app: db_rails
            appname: 0

      # delete the app
      - op: sequence
        actions:
          - action: delete_app
            appname: 0

  app_loop_spring:
    display: create and update a spring app

    appnames:
      - please-compute

    operations:
      # login, get situated, run vmc apps and services
      - op: sequence
        actions:
          - action: login
          - action: info

      # create a simple app
      - op: sequence
        actions:
          - action: create_app
            app: springtravel
            appname: 0
          - action: pause
            abs: 1
          - action: pause
            max: 4
          - action: update_app
            app: springtravel
            appname: 0

      # delete the app
      - op: sequence
        actions:
          - action: delete_app
            appname: 0

  app_loop_crash:
    display: create an app that crashes on boot.create and update a spring app

    appnames:
      - please-compute

    operations:
      # login, get situated, run vmc apps and services
      - op: sequence
        actions:
          - action: login
          - action: info

      # create a simple app
      - op: sequence
        actions:
          - action: create_app
            app: crashonboot
            appname: 0
          - action: pause
            abs: 1
          - action: pause
            max: 4

      # start/stop a bit
      - op: loop
        n: 4
        operations:
          - op: sequence
            actions:
              - action: stop_app
                appname: 0
              - action: start_app
                appname: 0
              - action: pause
                abs: 1
              - action: pause
                max: 4

      # delete the app
      - op: sequence
        actions:
          - action: delete_app
            appname: 0
