# Copyright (c) 2009-2013 VMware, Inc.
workloads:
  sys_sniff:
    display: vmc target + login + apps ~ developer ping
    load_multiplier: 10

    operations:
      # login, get situated
      - op: sequence
        actions:
          - action: info
          - action: login
          - action: apps

  sys_info:
    display: simulate vmc target
    load_multiplier: 12

    operations:
      # vmc target * 5
      - op: sequence
        actions:
          - action: info
          - action: info
          - action: info
          - action: info
          - action: info
