# Copyright (c) 2009-2013 VMware, Inc.
workloads:
  sys_basic_with_http:
    display: generic developer workload with a little http

    # set of static/dynamic appnames used in the template
    # all referenced by index in the various actions
    appnames:
      - please-compute
      - please-compute

    servicenames:
      - please-compute
      - please-compute

    operations:
      # login, get situated, run cf apps and services
      - op: sequence
        actions:
          - action: login

          - action: info
          - action: apps
          - action: apps
          - action: system_services
          - action: pause
            max: 10

      # create a simple app
      - op: sequence
        actions:
          - action: create_app
            app: foo
            appname: 0

      # iterate a few times, updating the app on each pass
      - op: loop
        n: 2
        operations:
          - op: sequence
            actions:
              - action: apps
              - action: app_info
                appname: 0
              - action: pause
                max: 10
              - action: update_app
                app: foo
                appname: 0
              - action: pause
                abs: 5
              - action: http_operation
                appname: 0
                path: /foo
                n: 50
                c: 2
              - action: http_operation
                appname: 0
                path: /bar
                n: 10
                c: 2
              - action: http_drain
              - action: pause
                max: 0

      # delete the app
      - op: sequence
        actions:
          - action: pause
            max: 10
          - action: delete_app
            appname: 0

  sys_basic_http_cpu:
    display: generic developer workload with heavy CPU in the test apps

    # set of static/dynamic appnames used in the template
    # all referenced by index in the various actions
    appnames:
      - please-compute
      - please-compute

    servicenames:
      - please-compute
      - please-compute

    operations:
      # login, get situated, run cf apps and services
      - op: sequence
        actions:
          - action: login
          - action: info
          - action: apps
          - action: info
          - action: system_services

      # create a simple app, ruby19, with http and cpu load endpoints
      - op: sequence
        actions:
          - action: create_app
            app: fib
            appname: 0

      # iterate a few times, updating the app on each pass
      - op: loop
        n: 2
        operations:
          - op: sequence
            actions:
              - action: login
              - action: info
              - action: apps
              - action: app_info
                appname: 0
              - action: pause
                max: 2
              - action: update_app
                app: fib
                appname: 0
              - action: pause
                abs: 5
              - action: app_info
                appname: 0
              - action: app_info
                appname: 0
              - action: http_operation
                appname: 0
                path: /foo
                n: 10
                c: 4
              - action: http_operation
                appname: 0
                path: /bar
                n: 10
                c: 2
              # fib is a very heavy cpu load
              - action: http_operation
                appname: 0
                path: /fib
                n: 8
                c: 2
              - action: http_drain
              - action: pause
                max: 0


      # delete the app
      - op: sequence
        actions:
          - action: pause
            abs: 5
          - action: delete_app
            appname: 0

  sys_basic:
    display: generic developer mix, no http workload

    appnames:
      - please-compute

    servicenames:
      - please-compute

    operations:
      # login, get situated, run cf apps and services
      - op: sequence
        actions:
          - action: login
          - action: info
          - action: apps
          - action: system_services
          - action: pause
            max: 10

      # create a simple app
      - op: sequence
        actions:
          - action: create_app
            app: foo
            appname: 0

      # iterate a few times, updating the app on each pass
      - op: loop
        n: 2
        operations:
          - op: sequence
            actions:
              - action: apps
              - action: app_info
                appname: 0
              - action: pause
                max: 10
              - action: update_app
                app: foo
                appname: 0

      # delete the app
      - op: sequence
        actions:
          - action: pause
            max: 10
          - action: delete_app
            appname: 0
