# Copyright (c) 2009-2013 VMware, Inc.
workloads:
  wip_placeholder:
    display: simulate cf target
    load_multiplier: 12

    operations:
      # cf target * 5
      - op: sequence
        actions:
          - action: info
          - action: info
          - action: info
          - action: info
          - action: info
